import React, { useState, useEffect } from 'react';
import { motion } from 'framer-motion';

const titleVariants = {
  hidden: { opacity: 0, y: -30 },
  visible: {
    opacity: 1,
    y: 0,
    transition: {
      type: "spring",
      stiffness: 80,
      damping: 15,
      duration: 0.6
    }
  }
};

const ROICalculator = () => {
  const [inputs, setInputs] = useState({
    claimsPerMonth: 1000,
    avgMinutesPerClaim: 45,
    rekeyRate: 20,
    hourlyCost: 50,
    automationRate: 70
  });

  const [results, setResults] = useState({
    hoursSaved: 0,
    costSaved: 0,
    paybackMonths: 0
  });

  // Calculate results whenever inputs change
  useEffect(() => {
    const calculateROI = () => {
      const totalClaimsPerMonth = inputs.claimsPerMonth;
      const totalMinutesPerMonth = totalClaimsPerMonth * inputs.avgMinutesPerClaim;
      const totalHoursPerMonth = totalMinutesPerMonth / 60;
      
      // Additional time for re-keying
      const rekeyHours = totalHoursPerMonth * (inputs.rekeyRate / 100);
      const totalHoursWithRekey = totalHoursPerMonth + rekeyHours;
      
      // Hours saved through automation
      const hoursSaved = totalHoursWithRekey * (inputs.automationRate / 100);
      const costSaved = hoursSaved * inputs.hourlyCost;
      
      // Assume monthly cost of solution is 30% of savings (placeholder)
      const monthlySolutionCost = costSaved * 0.3;
      const paybackMonths = monthlySolutionCost > 0 ? 1 / 0.7 : 0; // Simplified payback
      
      setResults({
        hoursSaved: Math.round(hoursSaved),
        costSaved: Math.round(costSaved),
        paybackMonths: Math.round(paybackMonths * 10) / 10
      });
    };

    calculateROI();
  }, [inputs]);

  const handleInputChange = (field, value) => {
    setInputs(prev => ({
      ...prev,
      [field]: Number(value)
    }));
  };

  const copyResults = async () => {
    const resultText = `
ROI Calculation Results:
• Claims per month: ${inputs.claimsPerMonth.toLocaleString()}
• Hours saved per month: ${results.hoursSaved.toLocaleString()}
• Cost saved per month: $${results.costSaved.toLocaleString()}
• Payback period: ${results.paybackMonths} months

Generated by AI Swiss Knife ROI Calculator
    `.trim();

    try {
      await navigator.clipboard.writeText(resultText);
      // Could add a toast notification here
    } catch (err) {
      console.error('Failed to copy results:', err);
    }
  };

  return (
    <section id="roi" className="py-16 sm:py-24 bg-white">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        <motion.div
          initial="hidden"
          whileInView="visible"
          viewport={{ once: true, amount: 0.2 }}
          variants={titleVariants}
          className="text-center mb-12"
        >
          <h2 className="text-3xl sm:text-4xl font-display font-bold text-neutral-900 mb-4">
            Calculate Your ROI
          </h2>
          <p className="text-lg text-neutral-600 max-w-2xl mx-auto">
            See the potential impact on your claims processing operation
          </p>
        </motion.div>

        <div className="grid lg:grid-cols-2 gap-12">
          {/* Input Section */}
          <motion.div
            initial={{ opacity: 0, x: -30 }}
            whileInView={{ opacity: 1, x: 0 }}
            viewport={{ once: true, amount: 0.2 }}
            transition={{ duration: 0.6 }}
            className="space-y-6"
          >
            <h3 className="text-xl font-semibold text-neutral-900 mb-6">Your Current Operation</h3>
            
            <div>
              <label htmlFor="claims-per-month" className="block text-sm font-medium text-neutral-700 mb-2">
                Claims processed per month
              </label>
              <input
                id="claims-per-month"
                type="number"
                value={inputs.claimsPerMonth}
                onChange={(e) => handleInputChange('claimsPerMonth', e.target.value)}
                className="w-full px-4 py-3 border border-neutral-300 rounded-lg focus:ring-2 focus:ring-swiss-red focus:border-swiss-red transition-colors"
                min="1"
              />
            </div>

            <div>
              <label htmlFor="avg-minutes" className="block text-sm font-medium text-neutral-700 mb-2">
                Average minutes per claim
              </label>
              <input
                id="avg-minutes"
                type="number"
                value={inputs.avgMinutesPerClaim}
                onChange={(e) => handleInputChange('avgMinutesPerClaim', e.target.value)}
                className="w-full px-4 py-3 border border-neutral-300 rounded-lg focus:ring-2 focus:ring-swiss-red focus:border-swiss-red transition-colors"
                min="1"
              />
            </div>

            <div>
              <label htmlFor="rekey-rate" className="block text-sm font-medium text-neutral-700 mb-2">
                Re-keying rate (%)
              </label>
              <input
                id="rekey-rate"
                type="number"
                value={inputs.rekeyRate}
                onChange={(e) => handleInputChange('rekeyRate', e.target.value)}
                className="w-full px-4 py-3 border border-neutral-300 rounded-lg focus:ring-2 focus:ring-swiss-red focus:border-swiss-red transition-colors"
                min="0"
                max="100"
              />
            </div>

            <div>
              <label htmlFor="hourly-cost" className="block text-sm font-medium text-neutral-700 mb-2">
                Average hourly cost ($)
              </label>
              <input
                id="hourly-cost"
                type="number"
                value={inputs.hourlyCost}
                onChange={(e) => handleInputChange('hourlyCost', e.target.value)}
                className="w-full px-4 py-3 border border-neutral-300 rounded-lg focus:ring-2 focus:ring-swiss-red focus:border-swiss-red transition-colors"
                min="1"
              />
            </div>

            <div>
              <label htmlFor="automation-rate" className="block text-sm font-medium text-neutral-700 mb-2">
                Expected automation rate (%)
              </label>
              <input
                id="automation-rate"
                type="number"
                value={inputs.automationRate}
                onChange={(e) => handleInputChange('automationRate', e.target.value)}
                className="w-full px-4 py-3 border border-neutral-300 rounded-lg focus:ring-2 focus:ring-swiss-red focus:border-swiss-red transition-colors"
                min="0"
                max="100"
              />
            </div>
          </motion.div>

          {/* Results Section */}
          <motion.div
            initial={{ opacity: 0, x: 30 }}
            whileInView={{ opacity: 1, x: 0 }}
            viewport={{ once: true, amount: 0.2 }}
            transition={{ duration: 0.6, delay: 0.2 }}
            className="bg-swiss-red/5 p-8 rounded-xl border border-swiss-red/20"
          >
            <h3 className="text-xl font-semibold text-neutral-900 mb-6">Projected Results</h3>
            
            <div 
              className="space-y-6"
              aria-live="polite"
              aria-label="ROI calculation results"
            >
              <div className="text-center p-6 bg-white rounded-lg shadow-sm">
                <div className="text-3xl font-bold text-swiss-red mb-2">
                  {results.hoursSaved.toLocaleString()}
                </div>
                <div className="text-neutral-600">Hours saved per month</div>
              </div>

              <div className="text-center p-6 bg-white rounded-lg shadow-sm">
                <div className="text-3xl font-bold text-swiss-red mb-2">
                  ${results.costSaved.toLocaleString()}
                </div>
                <div className="text-neutral-600">Cost saved per month</div>
              </div>

              <div className="text-center p-6 bg-white rounded-lg shadow-sm">
                <div className="text-3xl font-bold text-swiss-red mb-2">
                  {results.paybackMonths}
                </div>
                <div className="text-neutral-600">Months to payback</div>
              </div>
            </div>

            <motion.button
              onClick={copyResults}
              whileHover={{ scale: 1.02 }}
              whileTap={{ scale: 0.98 }}
              className="w-full mt-8 px-6 py-3 bg-swiss-red text-white rounded-lg font-semibold hover:bg-swiss-red/90 transition-colors focus:outline-none focus:ring-2 focus:ring-swiss-red focus:ring-offset-2"
            >
              Copy Results
            </motion.button>

            <p className="text-sm text-neutral-500 mt-4 text-center">
              <em>Calculations are estimates based on typical implementation results</em>
            </p>
          </motion.div>
        </div>
      </div>
    </section>
  );
};

export default ROICalculator;